In [1]:
#1) importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense

In [2]:
# 2)load the dataset
bank_note_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/training_set_label.csv" )
bank_note_data.head()

VWTI     SWTI     CWTI        EI  Class
0  2.2634  -4.4862   3.6558 -0.612510      0
1  3.2718   1.7837   2.1161  0.613340      0
2 -3.9411 -12.8792  13.0597 -3.312500      1
3  0.5195  -3.2633   3.0895 -0.984900      0
4  2.5698  -4.4076   5.9856  0.078002      0

In [3]:
# 3) getting the information about the columns
bank_note_data.info()
#there are no null entries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   VWTI    1096 non-null   float64
 1   SWTI    1096 non-null   float64
 2   CWTI    1096 non-null   float64
 3   EI      1096 non-null   float64
 4   Class   1096 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 42.9 KB


In [4]:
#4) separating input and output features
X=bank_note_data.drop('Class',axis=1)
y=bank_note_data.iloc[:,-1]

In [5]:
#4) splitting into training set and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
############################################

In [7]:
#building model


In [8]:
#1) initializing the model
model=tf.keras.Sequential()

#2)add input layer and hidden layers
model.add(Dense(10,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


#3)compiling the model
model.compile(optimizer='RMSprop',loss='binary_crossentropy',metrics=['accuracy'])


#3) training the model
model.fit(X_train,y_train,batch_size=32,epochs=100,verbose=1)




Epoch 1/100

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

28/28 [==============================] - 0s 1ms/step - loss: 0.7401 - accuracy: 0.3071
Epoch 2/100
28/28 [==============================] - 0s 1ms/step - loss: 0.6934 - accuracy: 0.4155
Epoch 3/100
28/28 [==============================] - 0s 983us/step - loss: 0.6721 - accuracy: 0.4806
Epoch 4/100
28/28 [==============================] - 0s 1ms/step - loss: 0.6525 - accuracy: 0.5240
Epoch 5/100
28/28 [==============================] - 0s 993us/step - loss: 0.6295 - accuracy: 0.5651
Epoch 6/1

In [9]:
#prediting  test set result
y_pred=(model.predict(X_test))

In [14]:
y_pred=y_pred>0.5
y_pred

array([[ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [

In [10]:
y_test

44     1
568    0
56     0
636    1
486    1
      ..
757    0
713    1
365    1
299    1
286    0
Name: Class, Length: 220, dtype: int64

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0

In [17]:
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/testing_set_label.csv')

In [18]:
predict=model.predict(test_data)

In [19]:
predict=predict>0.5

In [20]:
predict

array([[ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [21]:
c=1*predict

In [22]:
c

array([[1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
    

In [23]:
# To create Dataframe of predicted value with particular respective index
res = pd.DataFrame(c) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
res.index = test_data.index # its important for comparison. Here "test_new" is your new test dataset
res.columns = ["prediction"]

# To download the csv file locally
from google.colab import files
res.to_csv('prediction_results.csv')         
files.download('prediction_results.csv')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>